### ISSUE TITLE
can't change maxInverterInput-value

### ISSUE THREAD

**Issue by joe63** [reinhard-brandstaedter/solarflow-statuspage#47]
I disconnected my HUB2000 from cloud, therefore it's not possible to change some values. I took 400W for the maxInverterInput.
and now it's impossible to change the value. (1,2).
Is there a mqtt-order(command) which can overwrite the 400W maxInverterInput ( or the outputLimit)?

Also is there the question for me: should the inputs (3,4) have any effects for the program? I think, my instance will ignore the changed vales!

![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/6555368/f9b3c737-38ab-4298-8a0f-eb2afea60d7d)

at the end of charging, the output to home is max 400 W all the time .....
![image](https://github.com/reinhard-brandstaedter/solarflow-control/assets/6555368/27f85f1f-e615-4520-974e-08039ef89010)
green is the output of the inverter
red is the feedin-power and
blue is the used (from the inverter-produced ) power

**Comment by reinhard-brandstaedter** [comment]
fixed on other discussion
