### ISSUE TITLE
Since last update Output to home is limited during day

### ISSUE THREAD

**Issue by AzraelsDisk** [reinhard-brandstaedter/solarflow-statuspage#53]
![image](https://github.com/user-attachments/assets/5d7b1749-efdd-4158-9d4c-a0ee8232327b)
![image](https://github.com/user-attachments/assets/7663e642-e738-4a24-ae4d-3b6fe4fb301a)

It will switch between 1.2 and 2.1 if the value is above the 200 watt max limit.

My understanding was that "max" is used during the night... not during the day? 
Maybe I'm wrong or I don't understand the setting "discharge_during_daytime" as it is used.

Thanks
Azra

**Comment by AzraelsDisk** [comment]
wrong part of software

**Comment by AzraelsDisk** [comment]
done

**Comment by z-master42** [comment]
@AzraelsDisk then please close the issue.

**Comment by AzraelsDisk** [comment]
I tried it…Am 31.07.2024 um 09:19 schrieb z-master42 ***@***.***>:﻿
@AzraelsDisk then please close the issue.
